-- Jalankan SEKALI di Supabase SQL Editor
create table if not exists public.contact_messages (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  name text not null,
  email text not null,
  subject text not null,
  message text not null
);
alter table public.contact_messages enable row level security;
