'use server';
import crypto from 'crypto';
import {revalidatePath} from 'next/cache';
import {requireRole} from '@/lib/admin-auth';
import {createAdminClient} from '@/lib/supabase/admin';
function slugify(v:string){return v.toLowerCase().normalize('NFKD').replace(/[^a-z0-9\s-]/g,'').trim().replace(/\s+/g,'-').replace(/-+/g,'-').slice(0,120)}
function refresh(){for(const p of ['/admin','/writer','/admin/superadmin','/ruang-belajar','/cerita-makna','/layanan','/tentang','/kontak'])revalidatePath(p)}
export async function saveContent(formData:FormData){
 const {supabase,user,role}=await requireRole(['writer','admin','superadmin']); const title=String(formData.get('title')||'').trim();const section=String(formData.get('section')||'artikel');const body=String(formData.get('body')||'');const excerpt=String(formData.get('excerpt')||'').slice(0,420);let status=String(formData.get('status')||'draft');const folderId=String(formData.get('folder_id')||'')||null;let tableData:any=null;try{const raw=String(formData.get('table_json')||'');if(raw){const parsed=JSON.parse(raw);if(Array.isArray(parsed.headers)&&Array.isArray(parsed.rows)&&parsed.headers.some((x:any)=>String(x).trim())&&parsed.rows.some((r:any[])=>r.some(x=>String(x).trim())))tableData=parsed}}catch{}
 if(!title||!body||body.length>100000||!['ruang-belajar','artikel','layanan','tentang','kontak','ruang-jeda'].includes(section))throw new Error('Konten tidak valid.'); if(role==='writer'&&status==='published')status='review';if(!['draft','review','published'].includes(status))status='draft';
 let slug=slugify(String(formData.get('slug')||title)); if(!slug)slug=`konten-${Date.now()}`; const admin=createAdminClient(); const {data:dupe}=await admin.from('content_entries').select('id').eq('slug',slug).maybeSingle();if(dupe)slug=`${slug}-${crypto.randomBytes(3).toString('hex')}`;
 let attachment:any={}; const file=formData.get('attachment'); if(file instanceof File&&file.size){if(file.size>12582912||!['application/pdf','image/jpeg','image/png'].includes(file.type))throw new Error('Lampiran harus PDF/JPG/PNG maksimal 12 MB.');const ext=file.name.split('.').pop()?.toLowerCase()||'bin';const path=`${user.id}/${Date.now()}-${crypto.randomBytes(6).toString('hex')}.${ext}`;const bytes=Buffer.from(await file.arrayBuffer());const {error:up}=await supabase.storage.from('learning-materials').upload(path,bytes,{contentType:file.type,upsert:false});if(up)throw up;attachment={attachment_path:path,attachment_name:file.name.slice(0,180),attachment_mime:file.type,attachment_size:file.size};}
 const {error}=await supabase.from('content_entries').insert({title,slug,section,excerpt,body,status,folder_id:folderId,table_data:tableData,author_id:user.id,...attachment});if(error)throw error;refresh();
}
export async function setContentStatus(fd:FormData){const {supabase}=await requireRole(['admin','superadmin']);const id=String(fd.get('id'));const status=String(fd.get('status'));if(!['draft','review','published'].includes(status))throw new Error('Status invalid');const {error}=await supabase.from('content_entries').update({status,updated_at:new Date().toISOString()}).eq('id',id);if(error)throw error;refresh()}
export async function deleteContent(fd:FormData){const {supabase,user,role}=await requireRole(['writer','admin','superadmin']);const id=String(fd.get('id'));const {data:e}=await supabase.from('content_entries').select('author_id,attachment_path').eq('id',id).maybeSingle();if(!e)return;if(role==='writer'&&e.author_id!==user.id)throw new Error('Tidak diizinkan');if(e.attachment_path)await supabase.storage.from('learning-materials').remove([e.attachment_path]);const {error}=await supabase.from('content_entries').delete().eq('id',id);if(error)throw error;refresh()}
export async function saveFolder(fd:FormData){const {supabase}=await requireRole(['writer','admin','superadmin']);const name=String(fd.get('name')||'').trim().slice(0,100);const section=String(fd.get('section')||'ruang-belajar');if(!name)throw new Error('Nama folder wajib');let slug=slugify(name);const {error}=await supabase.from('content_folders').insert({name,slug,section});if(error)throw error;refresh()}
export async function deleteFolder(fd:FormData){const {supabase}=await requireRole(['admin','superadmin']);const id=String(fd.get('id'));await supabase.from('content_entries').update({folder_id:null}).eq('folder_id',id);const {error}=await supabase.from('content_folders').delete().eq('id',id);if(error)throw error;refresh()}
