'use client';
import {FormEvent,useEffect,useState} from 'react';import {createClient} from '@/lib/supabase/client';
type Mode='password'|'enroll'|'challenge'|'loading';
export default function AuthLogin({role,target,title}:{role:'writer'|'admin'|'superadmin';target:string;title:string}){const [mode,setMode]=useState<Mode>('password'),[msg,setMsg]=useState(''),[factorId,setFactorId]=useState(''),[qr,setQr]=useState(''),[busy,setBusy]=useState(false);const supabase=createClient();
 useEffect(()=>{(async()=>{const {data:{user}}=await supabase.auth.getUser();if(!user)return;await routeMfa(user.id)})()},[]);
 async function allowed(userId:string){const {data}=await supabase.from('admin_users').select('role,is_active').eq('user_id',userId).maybeSingle();return !!data?.is_active&&(role==='superadmin'?data.role==='superadmin':role==='admin'?['admin','superadmin'].includes(data.role):['writer','admin','superadmin'].includes(data.role))}
 async function routeMfa(userId:string){if(!(await allowed(userId))){await supabase.auth.signOut();setMsg('Akun tidak mempunyai akses untuk ruang ini.');setMode('password');return}const {data:f}=await supabase.auth.mfa.listFactors();const verified=f?.totp.find(x=>x.status==='verified');if(verified){setFactorId(verified.id);const {data:aal}=await supabase.auth.mfa.getAuthenticatorAssuranceLevel();if(aal?.currentLevel==='aal2'){window.location.replace(target);return}setMode('challenge');}else setMode('enroll')}
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setMsg('');const fd=new FormData(e.currentTarget);const {data,error}=await supabase.auth.signInWithPassword({email:String(fd.get('email')||'').trim(),password:String(fd.get('password')||'')});if(error||!data.user){setMsg('Email atau password tidak sesuai.');setBusy(false);return}await routeMfa(data.user.id);setBusy(false)}
 async function enroll(){setBusy(true);const {data,error}=await supabase.auth.mfa.enroll({factorType:'totp',friendlyName:`Menjadi Nol ${role}`});if(error||!data){setMsg(error?.message||'Gagal membuat MFA.');setBusy(false);return}setFactorId(data.id);setQr(data.totp.qr_code);setBusy(false)}
 async function verify(e:FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);const code=String(new FormData(e.currentTarget).get('code')||'');const {data:ch,error:ce}=await supabase.auth.mfa.challenge({factorId});if(ce||!ch){setMsg('Challenge MFA gagal.');setBusy(false);return}const {error}=await supabase.auth.mfa.verify({factorId,challengeId:ch.id,code});if(error){setMsg('Kode authenticator tidak sesuai.');setBusy(false);return}window.location.replace(target)}
 return <div className="auth"><section className="authVisual"><div><img src="/menjadi-nol-symbol.png"/><h2>MENJADI NOL</h2><p>Perjalanan pulang dalam diri</p><div className="securityPills"><span>Supabase Auth</span><span>RLS</span><span>MFA/TOTP</span></div></div></section><section className="authCard"><div className="form"><div className="eyebrow">SECURE ACCESS · {role.toUpperCase()}</div><h1>{title}</h1>{mode==='password'&&<form onSubmit={submit}><p>Login menggunakan akun khusus. Setelah password, akses dilindungi MFA/TOTP.</p><label>Email</label><input name="email" type="email" required autoComplete="email"/><label>Password</label><input name="password" type="password" required minLength={10} autoComplete="current-password"/><button className="btn" disabled={busy}>{busy?'Memeriksa…':'Masuk dengan aman'}</button></form>}{mode==='enroll'&&<div><p>Aktifkan MFA sebelum dashboard dibuka.</p>{!qr?<button className="btn" onClick={enroll} disabled={busy}>Buat QR Authenticator</button>:<><div className="qrBox"><img src={qr}/></div><form onSubmit={verify}><label>Kode 6 digit</label><input name="code" inputMode="numeric" pattern="[0-9]{6}" maxLength={6} required/><button className="btn">Aktifkan & lanjut</button></form></>}</div>}{mode==='challenge'&&<form onSubmit={verify}><p>Masukkan kode 6 digit dari aplikasi Authenticator.</p><label>Kode authenticator</label><input name="code" inputMode="numeric" pattern="[0-9]{6}" maxLength={6} required autoFocus/><button className="btn">Verifikasi</button></form>}{msg&&<p className="error">{msg}</p>}</div></section></div>}
