'use client';
import {useMemo,useRef,useState} from 'react';
import {saveContent,deleteContent,setContentStatus,saveFolder,deleteFolder} from './actions/content';
import TableBuilder from './TableBuilder';

type Entry={id:string;title:string;slug:string;section:string;excerpt?:string|null;body:string;status:'draft'|'review'|'published';author_id:string;attachment_name?:string|null;attachment_path?:string|null;created_at:string;updated_at?:string};
type Folder={id:string;name:string;slug:string;section:string;sort_order:number};
type View={created_at:string;session_hash:string;path:string};

export default function Dashboard({role,email,entries,folders,views=[]}:{role:'writer'|'admin'|'superadmin';email:string;entries:Entry[];folders:Folder[];views?:View[]}){
 const [tab,setTab]=useState<'overview'|'content'|'review'|'editor'|'folders'|'analytics'>('overview');
 const [query,setQuery]=useState('');const [status,setStatus]=useState('all');const [section,setSection]=useState('all');
 const [body,setBody]=useState(''); const [excerpt,setExcerpt]=useState(''); const [preview,setPreview]=useState(false); const bodyRef=useRef<HTMLTextAreaElement>(null);
 const filtered=useMemo(()=>entries.filter(e=>(status==='all'||e.status===status)&&(section==='all'||e.section===section)&&(!query||`${e.title} ${e.excerpt||''}`.toLowerCase().includes(query.toLowerCase()))),[entries,status,section,query]);
 const review=entries.filter(e=>e.status==='review'); const published=entries.filter(e=>e.status==='published').length; const draft=entries.filter(e=>e.status==='draft').length;
 const last7=useMemo(()=>Array.from({length:7},(_,i)=>{const d=new Date();d.setDate(d.getDate()-(6-i));return d.toISOString().slice(0,10)}),[]);
 const chart=last7.map(day=>views.filter(v=>v.created_at?.slice(0,10)===day).length); const max=Math.max(1,...chart); const unique30=new Set(views.map(v=>v.session_hash)).size;
 function wrap(before:string,after=before){const el=bodyRef.current;if(!el)return;const a=el.selectionStart,b=el.selectionEnd;const n=body.slice(0,a)+before+body.slice(a,b)+after+body.slice(b);setBody(n);requestAnimationFrame(()=>{el.focus();el.setSelectionRange(a+before.length,b+before.length)})}
 function insert(v:string){const el=bodyRef.current;if(!el)return;const a=el.selectionStart;setBody(body.slice(0,a)+v+body.slice(a));requestAnimationFrame(()=>{el.focus();el.setSelectionRange(a+v.length,a+v.length)})}
 const nav=[['overview','Dashboard'],['content','Konten'],['review',`Review${review.length?` (${review.length})`:''}`],['editor','Tulis Baru'],['folders','Folder Manager'],['analytics','Analytics']] as const;
 return <div className="dash"><aside className="side"><div className="brand adminBrand"><img src="/menjadi-nol-symbol.png"/><div><b>MENJADI NOL</b><small>{role}</small></div></div>{nav.map(([k,l])=><button key={k} className={tab===k?'sideActive':''} onClick={()=>setTab(k)}>{l}</button>)}{role==='superadmin'&&<a href="/admin/superadmin">Superadmin Control</a>}<a href="/">Lihat Website</a><a href="/api/staff/logout">Keluar</a></aside><main className="main">
 {tab==='overview'&&<><div className="eyebrow">DASHBOARD · {role.toUpperCase()}</div><h1 className="dashTitle">Selamat datang.</h1><p>{email}</p><div className="statgrid"><Stat n={entries.length} l="Total Konten"/><Stat n={published} l="Published"/><Stat n={review.length} l="Review"/><Stat n={draft} l="Draft"/></div><section className="panel"><h2>Konten terbaru</h2><EntryTable entries={entries.slice(0,8)} role={role}/></section></>}
 {tab==='content'&&<section className="panel"><div className="panelHead"><div><div className="eyebrow">CONTENT LIBRARY</div><h2>Semua konten</h2></div></div><div className="filters"><input placeholder="Cari judul…" value={query} onChange={e=>setQuery(e.target.value)}/><select value={status} onChange={e=>setStatus(e.target.value)}><option value="all">Semua status</option><option>draft</option><option>review</option><option>published</option></select><select value={section} onChange={e=>setSection(e.target.value)}><option value="all">Semua bagian</option><option value="ruang-belajar">Ruang Belajar</option><option value="artikel">Cerita & Makna</option><option value="layanan">Layanan</option><option value="tentang">Tentang</option><option value="ruang-jeda">Ruang Jeda</option><option value="kontak">Kontak</option></select></div><EntryTable entries={filtered} role={role}/></section>}
 {tab==='review'&&<section className="panel"><div className="eyebrow">REVIEW QUEUE</div><h2>Menunggu review</h2><EntryTable entries={review} role={role}/></section>}
 {tab==='editor'&&<section className="panel"><div className="eyebrow">EDITOR LENGKAP</div><h2>Tulis konten baru</h2><form action={saveContent} className="form wideForm" encType="multipart/form-data"><div className="grid2"><div><label>Judul</label><input name="title" required maxLength={180}/></div><div><label>Slug (opsional)</label><input name="slug" maxLength={120}/></div></div><div className="grid2"><div><label>Bagian</label><select name="section"><option value="ruang-belajar">Ruang Belajar</option><option value="artikel">Cerita & Makna</option><option value="layanan">Layanan</option><option value="tentang">Tentang</option><option value="ruang-jeda">Ruang Jeda</option><option value="kontak">Kontak</option></select></div><div><label>Fitur</label><select name="folder_id"><option value="">Tanpa fitur</option>{folders.map(f=><option key={f.id} value={f.id}>{f.section} · {f.name}</option>)}</select></div></div><label>Excerpt <span className="counter">{excerpt.length}/420</span></label><textarea name="excerpt" maxLength={420} value={excerpt} onChange={e=>setExcerpt(e.target.value)}/><label>Toolbar</label><div className="toolbar"><button type="button" onClick={()=>wrap('**')}>B</button><button type="button" onClick={()=>wrap('_')}>I</button><button type="button" onClick={()=>insert('\n# ')}>H1</button><button type="button" onClick={()=>insert('\n## ')}>H2</button><button type="button" onClick={()=>insert('\n> ')}>Quote</button><button type="button" onClick={()=>insert('\n- ')}>• List</button><button type="button" onClick={()=>insert('\n1. ')}>1. List</button><button type="button" onClick={()=>wrap('[','](https://)')}>Link</button><button type="button" onClick={()=>insert('\n---\n')}>Separator</button><button type="button" onClick={()=>insert('\n<div style="text-align:left">\n\n</div>')}>Kiri</button><button type="button" onClick={()=>insert('\n<div style="text-align:center">\n\n</div>')}>Tengah</button><button type="button" onClick={()=>insert('\n<div style="text-align:right">\n\n</div>')}>Kanan</button><button type="button" onClick={()=>insert('\n<!-- TOC -->\n')}>Daftar Isi</button></div><label>Isi <span className="counter">{body.length.toLocaleString('id-ID')}/100.000</span></label><textarea ref={bodyRef} className="editor" name="body" required maxLength={100000} value={body} onChange={e=>setBody(e.target.value)}/><TableBuilder/><label>Lampiran privat (PDF/JPG/PNG, maks 12 MB)</label><input name="attachment" type="file" accept="application/pdf,image/jpeg,image/png"/><div className="editorActions"><button className="btn alt" type="button" onClick={()=>setPreview(!preview)}>{preview?'Tutup Preview':'Preview'}</button><button className="btn alt" name="status" value="draft">Simpan Draft</button><button className="btn" name="status" value={role==='writer'?'review':'published'}>{role==='writer'?'Kirim Review':'Publikasikan'}</button></div>{preview&&<article className="preview"><h1>Preview</h1><p>{excerpt}</p><pre>{body}</pre></article>}</form></section>}
 {tab==='folders'&&<section className="panel"><div className="eyebrow">FITUR MANAGER</div><h2>Kelola fitur materi</h2><form action={saveFolder} className="folderForm"><input name="name" placeholder="Nama fitur" required maxLength={100}/><select name="section"><option value="ruang-belajar">Ruang Belajar</option><option value="artikel">Cerita & Makna</option><option value="layanan">Layanan</option></select><button className="btn">Tambah Fitur</button></form><div className="folderGrid">{folders.map(f=><div className="folderCard" key={f.id}><div><strong>{f.name}</strong><small>{f.section}</small></div>{role!=='writer'&&<form action={deleteFolder}><input type="hidden" name="id" value={f.id}/><button className="danger">Hapus</button></form>}</div>)}</div></section>}
 {tab==='analytics'&&<section className="panel"><div className="eyebrow">PRIVACY-FIRST ANALYTICS</div><h2>Aktivitas website</h2><div className="statgrid"><Stat n={views.length} l="Page views 30 hari"/><Stat n={unique30} l="Sesi unik"/><Stat n={views.filter(v=>Date.now()-new Date(v.created_at).getTime()<5*60000).length} l="Aktivitas 5 menit"/><Stat n={chart[6]||0} l="Views hari ini"/></div><div className="chart">{chart.map((v,i)=><div className="chartCol" key={last7[i]}><b>{v}</b><div className="barTrack"><i style={{height:`${Math.max(5,v/max*100)}%`}}/></div><small>{new Date(last7[i]).toLocaleDateString('id-ID',{weekday:'short'})}</small></div>)}</div></section>}
 </main></div>
}
function Stat({n,l}:{n:number;l:string}){return <div className="stat"><small>{l}</small><h2>{n}</h2></div>}
function EntryTable({entries,role}:{entries:Entry[];role:string}){if(!entries.length)return <p className="empty">Belum ada data.</p>;return <div className="tableWrap"><table><thead><tr><th>Judul</th><th>Bagian</th><th>Status</th><th>Lampiran</th><th>Aksi</th></tr></thead><tbody>{entries.map(e=><tr key={e.id}><td><strong>{e.title}</strong><small>/{e.slug}</small></td><td>{e.section}</td><td><span className={`badge ${e.status}`}>{e.status}</span></td><td>{e.attachment_path?<a href={`/api/attachments/${e.id}`} target="_blank">{e.attachment_name||'Buka'}</a>:'—'}</td><td><div className="rowActions">{role!=='writer'&&e.status!=='published'&&<form action={setContentStatus}><input type="hidden" name="id" value={e.id}/><input type="hidden" name="status" value="published"/><button>Publish</button></form>}{role!=='writer'&&e.status==='published'&&<form action={setContentStatus}><input type="hidden" name="id" value={e.id}/><input type="hidden" name="status" value="draft"/><button>Unpublish</button></form>}<form action={deleteContent}><input type="hidden" name="id" value={e.id}/><button className="danger">Hapus</button></form></div></td></tr>)}</tbody></table></div>}
