-- MENJADI NOL — FULL SECURE migration (idempotent where possible)
create extension if not exists pgcrypto;

create table if not exists public.reader_users(
  user_id uuid primary key references auth.users(id) on delete cascade,
  email text unique not null,
  name text,
  created_at timestamptz not null default now()
);

create table if not exists public.reader_email_otps(
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.reader_users(user_id) on delete cascade,
  email text not null,
  code_hash text not null,
  attempts int not null default 0 check(attempts between 0 and 5),
  expires_at timestamptz not null,
  used_at timestamptz,
  created_at timestamptz not null default now()
);
create index if not exists reader_email_otps_lookup on public.reader_email_otps(user_id,created_at desc);

create table if not exists public.admin_users(
  user_id uuid primary key references auth.users(id) on delete cascade,
  email text,
  display_name text,
  role text not null check(role in('writer','admin','superadmin')),
  is_active boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public.writer_applications(
 id uuid primary key default gen_random_uuid(),
 name text not null,email text not null,message text,
 status text not null default 'pending' check(status in('pending','approved','rejected')),
 created_at timestamptz not null default now()
);

create table if not exists public.content_folders(
 id uuid primary key default gen_random_uuid(),
 name varchar(100) not null,
 slug varchar(120) not null,
 section text not null check(section in('ruang-belajar','artikel','layanan','tentang','kontak','sinopsis')),
 sort_order int not null default 0,
 created_at timestamptz not null default now(),
 unique(section,slug)
);

create table if not exists public.content_entries(
 id uuid primary key default gen_random_uuid(),
 title varchar(180) not null,
 slug varchar(120) unique not null,
 section text not null check(section in('ruang-belajar','artikel','layanan','tentang','kontak','sinopsis')),
 folder_id uuid references public.content_folders(id) on delete set null,
 excerpt varchar(420),
 body text not null check(char_length(body)<=100000),
 table_data jsonb,
 status text not null default 'draft' check(status in('draft','review','published')),
 author_id uuid not null references auth.users(id),
 attachment_path text,attachment_name text,attachment_mime text,attachment_size bigint,
 created_at timestamptz not null default now(),updated_at timestamptz not null default now()
);
alter table public.content_entries add column if not exists folder_id uuid references public.content_folders(id) on delete set null;
alter table public.content_entries add column if not exists table_data jsonb;
alter table public.content_entries add column if not exists attachment_path text;
alter table public.content_entries add column if not exists attachment_name text;
alter table public.content_entries add column if not exists attachment_mime text;
alter table public.content_entries add column if not exists attachment_size bigint;

create table if not exists public.page_views(
 id bigint generated by default as identity primary key,
 path text not null,
 session_hash text not null,
 created_at timestamptz not null default now()
);
create index if not exists page_views_created_idx on public.page_views(created_at desc);

alter table public.reader_users enable row level security;
alter table public.reader_email_otps enable row level security;
alter table public.admin_users enable row level security;
alter table public.writer_applications enable row level security;
alter table public.content_folders enable row level security;
alter table public.content_entries enable row level security;
alter table public.page_views enable row level security;

-- Helper functions used by RLS.
create or replace function public.is_active_staff() returns boolean language sql stable security definer set search_path=public as $$
 select exists(select 1 from public.admin_users a where a.user_id=auth.uid() and a.is_active)
$$;
create or replace function public.is_admin() returns boolean language sql stable security definer set search_path=public as $$
 select exists(select 1 from public.admin_users a where a.user_id=auth.uid() and a.is_active and a.role in('admin','superadmin'))
$$;
create or replace function public.is_superadmin() returns boolean language sql stable security definer set search_path=public as $$
 select exists(select 1 from public.admin_users a where a.user_id=auth.uid() and a.is_active and a.role='superadmin')
$$;

-- Staff can read their own access row; superadmin can manage all rows.
drop policy if exists "staff read self" on public.admin_users;
create policy "staff read self" on public.admin_users for select to authenticated using(user_id=auth.uid() or public.is_superadmin());
drop policy if exists "superadmin manage staff" on public.admin_users;
create policy "superadmin manage staff" on public.admin_users for all to authenticated using(public.is_superadmin()) with check(public.is_superadmin());

-- Published content/folders may be read by app server. Staff AAL2 can manage.
drop policy if exists "staff select content" on public.content_entries;
create policy "staff select content" on public.content_entries for select to authenticated using((select auth.jwt()->>'aal')='aal2' and public.is_active_staff());
drop policy if exists "staff insert content" on public.content_entries;
create policy "staff insert content" on public.content_entries for insert to authenticated with check(author_id=auth.uid() and (select auth.jwt()->>'aal')='aal2' and public.is_active_staff());
drop policy if exists "staff update content" on public.content_entries;
create policy "staff update content" on public.content_entries for update to authenticated using((select auth.jwt()->>'aal')='aal2' and public.is_active_staff() and (author_id=auth.uid() or public.is_admin())) with check((select auth.jwt()->>'aal')='aal2' and public.is_active_staff());
drop policy if exists "staff delete content" on public.content_entries;
create policy "staff delete content" on public.content_entries for delete to authenticated using((select auth.jwt()->>'aal')='aal2' and public.is_active_staff() and (author_id=auth.uid() or public.is_admin()));

drop policy if exists "staff select folders" on public.content_folders;
create policy "staff select folders" on public.content_folders for select to authenticated using((select auth.jwt()->>'aal')='aal2' and public.is_active_staff());
drop policy if exists "staff insert folders" on public.content_folders;
create policy "staff insert folders" on public.content_folders for insert to authenticated with check((select auth.jwt()->>'aal')='aal2' and public.is_active_staff());
drop policy if exists "admin update folders" on public.content_folders;
create policy "admin update folders" on public.content_folders for update to authenticated using((select auth.jwt()->>'aal')='aal2' and public.is_admin());
drop policy if exists "admin delete folders" on public.content_folders;
create policy "admin delete folders" on public.content_folders for delete to authenticated using((select auth.jwt()->>'aal')='aal2' and public.is_admin());

drop policy if exists "staff read analytics" on public.page_views;
create policy "staff read analytics" on public.page_views for select to authenticated using((select auth.jwt()->>'aal')='aal2' and public.is_admin());

insert into storage.buckets(id,name,public,file_size_limit,allowed_mime_types)
values('learning-materials','learning-materials',false,12582912,array['application/pdf','image/jpeg','image/png'])
on conflict(id) do update set public=false,file_size_limit=excluded.file_size_limit,allowed_mime_types=excluded.allowed_mime_types;

drop policy if exists "staff upload learning materials" on storage.objects;
create policy "staff upload learning materials" on storage.objects for insert to authenticated with check(bucket_id='learning-materials' and (select auth.jwt()->>'aal')='aal2' and public.is_active_staff());
drop policy if exists "staff update learning materials" on storage.objects;
create policy "staff update learning materials" on storage.objects for update to authenticated using(bucket_id='learning-materials' and (select auth.jwt()->>'aal')='aal2' and public.is_active_staff()) with check(bucket_id='learning-materials' and public.is_active_staff());
drop policy if exists "staff delete learning materials" on storage.objects;
create policy "staff delete learning materials" on storage.objects for delete to authenticated using(bucket_id='learning-materials' and (select auth.jwt()->>'aal')='aal2' and public.is_active_staff());

drop policy if exists "reader insert self" on public.reader_users;
create policy "reader insert self" on public.reader_users for insert to authenticated with check(user_id=auth.uid());
drop policy if exists "reader read self" on public.reader_users;
create policy "reader read self" on public.reader_users for select to authenticated using(user_id=auth.uid());

-- Automatically create reader profile after Auth sign-up; staff invitations are ignored.
create or replace function public.handle_new_reader() returns trigger
language plpgsql security definer set search_path=public as $$
begin
  if coalesce(new.raw_user_meta_data->>'account_type','')='reader' then
    insert into public.reader_users(user_id,email,name)
    values(new.id,coalesce(new.email,''),new.raw_user_meta_data->>'name')
    on conflict(user_id) do update set email=excluded.email,name=coalesce(excluded.name,public.reader_users.name);
  end if;
  return new;
end;$$;
drop trigger if exists on_auth_user_created_reader on auth.users;
create trigger on_auth_user_created_reader after insert or update of raw_user_meta_data,email on auth.users for each row execute procedure public.handle_new_reader();
