-- 010_dashboard_analytics.sql
-- Analytics anonim dan privacy-first untuk dashboard kembali ke nol.

create table if not exists public.page_views (
  id bigint generated by default as identity primary key,
  session_id text not null
    check (char_length(session_id) between 8 and 100),
  path text not null
    check (char_length(path) between 1 and 500),
  referrer text
    check (referrer is null or char_length(referrer) <= 500),
  device_type text not null default 'unknown'
    check (device_type in ('mobile','desktop','tablet','unknown')),
  created_at timestamptz not null default now()
);

create index if not exists page_views_created_at_idx
  on public.page_views (created_at desc);

create index if not exists page_views_session_id_idx
  on public.page_views (session_id);

create index if not exists page_views_path_idx
  on public.page_views (path);

alter table public.page_views enable row level security;

drop policy if exists "anon can insert page views" on public.page_views;
create policy "anon can insert page views"
on public.page_views
for insert
to anon, authenticated
with check (
  char_length(session_id) between 8 and 100
  and char_length(path) between 1 and 500
);

drop policy if exists "admins can read page views" on public.page_views;
create policy "admins can read page views"
on public.page_views
for select
to authenticated
using (
  exists (
    select 1
    from public.admin_users au
    where au.user_id = auth.uid()
  )
);

-- Status review untuk workflow konten.
alter table public.content_folder_entries
  drop constraint if exists content_folder_entries_status_check;

alter table public.content_folder_entries
  add constraint content_folder_entries_status_check
  check (status in ('draft','review','published'));
